### ISSUE TITLE
question: seems useful, but I get a bad feeling from writing a docstring?

### ISSUE THREAD

**Issue by kootenpv** [erikrose/parsimonious#105]
Hey, I really like the possibilities, but I'm a bit "worried" about writing strings. Naturally, our editor won't help. Do you maybe have some advice on that? Why is it implemented like that?

**Comment by erikrose** [comment]
I'm not sure what you mean. Can you be more specific, please?

**Comment by kootenpv** [comment]
Grammar accepts a multi-line sentence, aka doc string, but we do not get any highlighting within this string for types.

**Comment by erikrose** [comment]
Ah. Strings are generally considered "docstrings" only when used, as the first statement of a Python construct, to document that construct. That's why I didn't understand.

Parsimonious's grammars are expressed as strings in order to make them look as much like PEGs (or even EBNFs, sort of) as possible without having to do a lot of roundabout coding to wedge them into a Python-object style. PyParsing does the latter, and the result is, to my eyes, less readable. It also prevents you from making forward references without predeclarations, since Python would complain of NameErrors.

I don't know of any editor that would, out of the box, do useful highlighting on a Parsimonious grammar even if they weren't contained in strings. However, most popular editors are sufficiently customizable that you could probably put something together, even given the string containers. I'd be very interested to see anything you come up with!
