### ISSUE TITLE
Recursion Error

### ISSUE THREAD

**Issue by ibigpapa** [erikrose/parsimonious#116]
I hit the recursion error while attempting to parse a text with this grammar.  I'm guessing my grammar is to blame for this.    Or is it because my text i'm parsing is nasty?

### Grammar
```python
grammar = Grammar(r"""
    config = line+ EOF
    block = generic_block
    generic_block = statement block_start line+ block_end
    block_start = block_start_word new_line
    block_end = block_start_word new_line
    line = (block / comment / statement)
    statement = generic_statement
    generic_statement = words+ new_line
    words = word (space word)* space*
    word = ~"[a-z0-9\.\:\-\/\(\)\,\@\_]+"i
    comment = comment_char (space / words)* new_line
    comment_char = "!"
    new_line = ~"\n"
    block_start_word = "BLOCK_START"
    block_end_word = "BLOCK_END"
    EOF = "EOF"
""")
```

### Example Text
```python
text = """a statement line
!
a block statement line
BLOCK_START
sub block statement line
!
sub block block statement line
BLOCK_START
sub sub block statement line
BLOCK_END
sub block statement line 2
!
BLOCK_END
EOF"""

**Comment by pylang** [comment]
I got differ errors and notices some minor issues in this grammar, e.g. lack of `space` rule and and alternative top rule.  The following grammar parses your sample `text`. 

```python
grammar = pars.grammar.Grammar(
    r"""
    config            = block+ / non_block+
  
    block             = eof / block_start / block_end / block_line
    non_block         = eof / line
    block_line        = comment / statement
    line              = comment / statement
    
    block_start       = "BLOCK_START" newline
    block_end         = "BLOCK_END" newline    
    statement         = text newline
    comment           = "!" text newline
    eof               = "EOF"

    newline           = ~r"\n*"
    text              = ~r"[A-z0-9 ]*"i
    
    """
)
```

Regarding the AST, this will not completely give you what you are looking for, but it is close.  Ideally, you might want a  rule such as  `config = block+ / non_block+`, but some challenges were: 

1. Distinguishing a line as part of a `block` vs. a regular `non_block` is difficult since they share a common regex.
1. The presence of newline characters for all lines except EOF (optional) made rules with `newline*` raises errors due to nuisance empty `"" Nodes `. 

![rect3007-1](https://user-images.githubusercontent.com/10778668/28330644-55614b56-6bbc-11e7-813f-4de35964d433.png)

What would be preferable is an idiom for distinguishing non-block (lineno 2, 3, 15) and block structures (remaining lineno).  This would further allow parsing of python suites (`for`, `if-else`, `class`) verses statements such as single-line assignments.  I imagine this is possible with `parsmoninous`, but I am unable to figure out how.

@erikrose, how does one parse both a block of code separate from other lines using a single grammar?

**Comment by erikrose** [comment]
@pylang I'm not sure what you're asking. In general, when trying to parse a block-structured language, you have a rule much like @ibigpapa did, something along the lines of…

```
suite = simple_stmt | NEWLINE BEGIN stmt+ END
```

This is adapted from [Python's own grammar](https://docs.python.org/3/reference/grammar.html), which is a pretty good example of how to structure something without going mad.

**Comment by erikrose** [comment]
@ibigpapa Just from the shortness of your text, I strongly suspect your grammar. (And I apologize that debugging grammars is presently so hard. It's an area I intend to make major strides in someday.)

I suggest you focus your thought on recursive areas of your grammar, like this:

```
    block = generic_block
    generic_block = statement block_start line+ block_end
    line = (block / comment / statement)
```

In the above, `block` looks for a `generic_block`, which looks for a `line`, which looks for a `block` again. This may be what you intended, but some cycle like that is almost certainly happening in an *un*intended place, driving you to overdeep recursion.
