### ISSUE TITLE
Ommitting things without creating a node

### ISSUE THREAD

**Issue by schmittlauch** [erikrose/parsimonious#117]
I'm currently trying to parse a file which contains arbitrary description before the relevant data starts. I need to skip this part until I find the first data identifier, all things before the first identifier are later to be ignored.

As REs seem to behave greedily in PEG parsers I eat away the arbitrary characters one by one, each creating 2 nodes. That's probably the rason of the `RecursionError` I'm currently getting.

The relevant part of my grammar looks like this:

```PEG
        start           = skip_preface
        skip_preface    = instance_list / (~"."s skip_preface)
```

I'd later throw away all `skip_preface` matches anyway, so is there a way to just omit/ ignore this? If not, is there a better way to deal with the preface?

**Comment by schmittlauch** [comment]
It probably was my grammar. I switched to arpeggio for now, but I assume it's not parsimonious to blame.

**Comment by erikrose** [comment]
Arguably Parsimonious is to blame, since we could do trampolining to support arbitrarily deep recursion, something I've been idly considering for some time. This is the first time I've seen someone run into the limit in real life; thanks for bringing it back to top of mind. The usual solution in PEGs is to express things non-recursively when possible, using `+` or `*` quantifiers.

**Comment by schmittlauch** [comment]
I assume in this case it was still my grammar to blame as I ran into recursion errors with arpeggio too before fixing my grammar.

If I find the time I can try out my working grammar with parsimonious again.

**Comment by erikrose** [comment]
Ah, thanks for letting me know!
