### ISSUE TITLE
parsing markdown lists and sublists

### ISSUE THREAD

**Issue by pylang** [erikrose/parsimonious#125]
I have done a lot with parsimonious to extract text from a markdown file.  I appreciate the ease this library offers in doing this.  The only major bottleneck I've had is parsing lists from sublists.  Example:

```
1. Item A
2. Item B
3. Block C
    1. Sub-item C.1
    2. Sub-block C.2
       a. Sub-block C.2.a
            1. Sub-item C.2.a1  
```

These blocks are distinguished by indent levels.  I need to parse the following as distinct nodes:
- an item (0 indent)
- a block (header 0, sub-item 1) 
- a sub-block (header 1, sub-items 2 or more indents) 

I understand indenting is not something PEG parsers traditionally do, but is there any hope of using parsimonious to distinguish these blocks of text?

**Comment by erikrose** [comment]
Sure! The right approach depends on the shape of the tree you want out. If you want just a list of items, without nesting represented, you can do something naive like saying "All lines that begin with 8 spaces are sub-subitems!"

But if you want nesting represented (more likely), you break outside the bounds of what PEGs can handle, into context-sensitive grammars. This one is context-sensitive because what you really want to express is "This line is indented, relative to the last one," and the "relative to" makes the determination of this sensitive to the context—that is, the previous line. How I've approached this in Parsimonious before is to roll my own lexer (see https://github.com/erikrose/turtles/blob/master/lexing.py for a half-working example) and then use the experimental TokenGrammar rather than the normal Grammar. The main difference in use is that, in TokenGrammars, `"foo"` refers not to a literal string "foo" but to tokens of `.type` foo. The rest is the same. Does that get you moving in the right direction?

**Comment by pylang** [comment]
I am starting to put in the time into traversing the learning curve. I understand it more and may revisit.

Thank you.  Closing this.
