### ISSUE TITLE
AttributeError: 'LazyReference' object has no attribute 'match_core'

### ISSUE THREAD

**Issue by kkleidal** [erikrose/parsimonious#134]
```
File "/usr/local/src/anaconda3/lib/python3.6/site-packages/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/usr/local/src/anaconda3/lib/python3.6/site-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/src/anaconda3/lib/python3.6/site-packages/parsimonious/expressions.py", line 411, in _uncached_match
    node = self.members[0].match_core(text, pos, cache, error)
  File "/usr/local/src/anaconda3/lib/python3.6/site-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/src/anaconda3/lib/python3.6/site-packages/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
AttributeError: 'LazyReference' object has no attribute 'match_core'
```

I keep encountering this strange error while parsing :/.  If I perturb the grammar slightly, it goes away, but I often run into it again while expanding the grammar further.   Any ideas?

Version:  0.8.0, installed via pip, Python 3.6.3, Anaconda (64-bit), Ubuntu 16.04.

Thanks for the great library, btw.

**Comment by erikrose** [comment]
Hmm, there shouldn't be any LazyReferences left after the grammar is compiled. Can you show me how you're using the grammar once you've instantiated it?

**Comment by erikrose** [comment]
Never mind; I happened into the same problem myself!

**Comment by miketrim** [comment]
I had a look into this issue. It seems to be caused by identical unnamed expressions in the grammar (such as item* in the above test case).  When the references are resolved, the first occurence of the expression is added to the 'done' set, and then when the second occurrence is resolved it compares equal to the first because they are the same class and have the same members. I was able to work around the issue by defining named expressions for problematic subexpressions.  There must be some further subtleties as it only seems to happen for some cases, I think something to do with the fact that the expression's members are only rewritten once all the members have been processed.

**Comment by miketrim** [comment]
I've been able to 'fix' the issue (at least for the cases I have tried) by modifying _resolve_refs to only add named expressions to the 'done' set.  I guess it is not possible to recurse through unnamed expressions, so this should be safe.

**Comment by erikrose** [comment]
That's interesting. When I chased it down, it seemed to be that we need to replace the existing algorithm, which assumes there's basically a tree of expressions we can recurse down, with a Dijkstra-style graph traversal. I have a start at it;  just need to find a several-hour span to sit down and finish.

**Comment by righthandabacus** [comment]
FYI: The failing check is due to Travis CI build, shouldn't be my fault.
