### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by swayson** [erikrose/parsimonious#166]
Hi there,

I am curious whether this library is still being maintained and taking PRs? @erikrose 

It is a really good lib, and would be sad to see it go stale.

**Comment by erikrose** [comment]
I'm looking for helpers to review PRs, as I've been busy with [concentrations](https://github.com/mozilla/fathom/) [elsewhere](https://github.com/mozilla/sphinx-js/). Would you or the thumbs-uppers be interested? This is still the parsing library I reach for, and I still think it's important to have a good parsing lib around that decouples grammars from visitors. (The speed thing has become less of a focus now that non-pure-Python can be deployed easily and securely.)

**Comment by evanh** [comment]
I'm interested in helping out with this. I've been working a lot with it recently and it's super useful.

**Comment by erikrose** [comment]
Thanks, @evanh! I'd be more than  pleased to have your help. Do you want to start by looking over and commenting on some of the existing PRs, and then I'll do a meta-review, until our brains come into alignment? After a couple go well, I'll give you commit access, and we can go from there.

Just off the top of my head, these are my top priorities for Parsimonious:

* Docs, which I have half-written on a [branch](https://github.com/erikrose/parsimonious/tree/docs)
* Fixing a bug I suspect exists where certain things passed to Visitors are iterables when they shouldn't be
* [Reversing the precedence of And and Or](https://github.com/erikrose/parsimonious/tree/lower-precedence-ors), which is accidentally out of line with what every other PEG parser (and the original paper) do
* Making visitors easier to write. We lost a lot of ergonomics with the transition to Python 3, since it no longer supports auto-unpacking into tuples in methods' formal param lists. Maybe do some `inspect` magic or something to match up with arg names (or kwargs, or something—design needed). Also, maybe don't bother passing constant terms (like "foo") to the visitor methods at all, for brevity; they're rarely useful. This would dovetail nicely with a revised param format, since the constant terms lack names.

Of course, since it's open-source, I'm quite open to others priorities, driven by the community. It's just fallen way down my priority list.

And of course, there's lot of infra cleanup to do. We should drop nose, which is obsolete. We should update the versions of Python we use in CI and drop support for Python 2. There are PRs open for both of those.

Thanks again!

**Comment by swayson** [comment]
Hi, I can help out but will need guidance from you guys on what to tackle.

**Comment by erikrose** [comment]
@swayson Thank you! You could review #135 or open a PR for the patch pointed to in #160. Or attack any of the bulleted priorities I mentioned above. If none of that excites you, we have a lot of open issues! If you list a few that appeal to you, I'd be happy to give an initial impression of whether they're worth pursuing.

**Comment by lonnen** [comment]
Thank you for the submissions, @swayson 

closing this out for now

**Comment by alexchandel** [comment]
@evanh / @swayson are you still maintaining this, or is it unmaintained again?
