### ISSUE TITLE
Support python3.7

### ISSUE THREAD

**Issue by whme** [erikrose/parsimonious#167]
When trying to install [sphinx-js](https://pypi.org/project/sphinx-js/) with python3.7 it cannot satisfy the parsimonious requirement. I suppose this is because parsimonious doesn't support python3.7 or is simply not tagged as doing so.

**Comment by johns1c** [comment]
Dear all,
A very quick check shows that parsimonious installs and runs (at least the first bit of code in the readme) ok in both python 3.7 and 3.8.  

I just did a pip install of sphinx-js on python 3.8 and python 3.7 on windows and  (in my environment at least) the pip install of sphnx-js installs or downgrades parsimonious to 0.7.0.
I suspect that some other product has a dependency on a different version of  parsimonious.  If not perhaps we have conflicting requirements on six.  

Chris J

 works but I have not tested sphinx.js.
what is failing?   The  
what operating system?


is it the install that is failing or is it     
will see what happens on python 3.7


Chris J



    On Wednesday, 26 August 2020, 12:03:07 BST, whme <notifications@github.com> wrote:  
 
 


When trying to install sphinx-js with python3.7 it cannot satisfy the parsimonious requirement. I suppose this is because parsimonious doesn't support python3.7 or is simply not tagged as doing so.

**Comment by whme** [comment]
Your right, I discovered I had a rather strange mixture of different python versions. Sorry for the inconvenience.

**Comment by erikrose** [comment]
Thanks so much for chiming in, @johns1c!
