### ISSUE TITLE
Nodes in the AST do not have names when used in conjunction with ?, +, *, ...

### ISSUE THREAD

**Issue by r41d** [erikrose/parsimonious#66]
Here is a part of my Grammar:
```
ping_statistics = entry+
entry = int entry_body? NWL
entry_body = NWL header NWL ping+ NWL stats
```
I created visit_* methods for each of entry, entry_body and ping.
But these methods do not get called.
In the AST they look like ```<Node matching "...">```
The name is there when i remove the ? on entry_body.

My workaround looks like this:
```
def visit_(self, node, contents):
	if len(contents) < 1:
		return None          ## generic string constant matcher..
	if len(contents) == 1:
		return contents[0]       ##  entry_body?
	return contents
```

Nodes shouldnt lose their names when used in conjunction with ?, +, *, ...

**Comment by gcq** [comment]
I can reproduce this too on my side. i have to move the modifiers to the root rule for it to work. Which makes grammars a little less intuitive.

**Comment by ufukk** [comment]
I have the same problem.

**Comment by merrickheley** [comment]
I also have this problem. It's a big issue that is preventing me from making good use of this library.

**Comment by erikrose** [comment]
I apologize for the sparse documentation. Let me try to clear this behavior up:

The node emitted that represents `ping+`, for example, should not have a name. But it will contain one or more child nodes (because of the `+`) that will have the `expr_name` "ping". That way, you can write the handling of `ping` nodes one time, in `visit_ping()`, and have it automatically used for `ping`, `ping+`, `ping*`, etc. If you want special handling for `ping+`, I recommend breaking it off so it too has a name, like this:

```
entry_body = NWL header NWL pings NWL stats
pings = ping+
```
It will run no less efficiently. Then you can write a `visit_pings()` to do the special handling.

Please reopen if I've missed the point of your problem. Thanks!
