### ISSUE TITLE
Handle indentation

### ISSUE THREAD

**Issue by gcq** [erikrose/parsimonious#67]
Is there any way to handle indentation levels in parsimonious?

I'm debating of sucking up all whitespace in front of each line, and try to take care of it with visitors, but i'm not sure how that would work out.

**Comment by codeyash** [comment]
Try this one : https://github.com/igordejanovic/Arpeggio
I'm not author but i like this one. It gives us option to treat whitespace in our style. 

I don't there is inbuilt option in parsimonious

**Comment by erikrose** [comment]
Pure PEGs can't handle significant indentation on their own, but there are a variety of hacks you could apply. For example, http://stackoverflow.com/questions/4205442/peg-for-python-style-indentation has some ideas.

The other escape value is Parsimonious's "custom rules". You may be able to do something clever inside one of those. You almost certainly could if you disabled caching—which isn't supported at the moment, but making it possible wouldn't be that hard; caching isn't even a clear win for many grammars. Then you could close over some state (like the indentation level) in your custom rule and do whatever you liked.

**Comment by erikrose** [comment]
Yet another option, suitable for some languages, is to do your own lexing and use Parsimonious only for parsing. You'd emit [Token](https://github.com/erikrose/parsimonious/blob/8782d50e5fae587edb14a686de8e2e04fb61e68a/parsimonious/utils.py#L31) subclasses and use [TokenGrammar](https://github.com/erikrose/parsimonious/blob/8782d50e5fae587edb14a686de8e2e04fb61e68a/parsimonious/grammar.py#L152) instead of Grammar. (This is still an experimental feature.)

**Comment by ibigpapa** [comment]
@erikrose when using the [TokenGrammar](https://github.com/erikrose/parsimonious/blob/8782d50e5fae587edb14a686de8e2e04fb61e68a/parsimonious/grammar.py#L152) is it matching against the ``type`` attribute of the  [Token](https://github.com/erikrose/parsimonious/blob/8782d50e5fae587edb14a686de8e2e04fb61e68a/parsimonious/utils.py#L31) subclasses?

**Comment by erikrose** [comment]
Yes.

**Comment by ibigpapa** [comment]
Excellent Thanks I'm dealing with the indentation issue as well.  Turns out the token grammar allows me to create a more complex structure after creating a simple structure using regex to create tokens.

in case anyone else wants to know how to do this.  Here's the getting started sample done with the TokenGrammar.
```python
>>> from parsimonious.utils import Token
>>> from parsimonious import TokenGrammar
>>> grammar = TokenGrammar("""
... bold_text = bold_open text bold_close
... text = "TEXT"
... bold_open = "BOLD_OPEN"
... bold_close = "BOLD_CLOSE"
... """)
>>> tl = []
>>> tl.append(Token(type='BOLD_OPEN'))
>>> tl.append(Token(type='TEXT'))
>>> tl.append(Token(type='BOLD_CLOSE'))
```

```python
>>> print(grammar.parse(tl))
<Node called "bold_text" matching "[<Token "BOLD_OPEN">, <Token "TEXT">, <Token "BOLD_CLOSE">]">
    <Node called "bold_open" matching "[<Token "BOLD_OPEN">]">
    <Node called "text" matching "[<Token "TEXT">]">
    <Node called "bold_close" matching "[<Token "BOLD_CLOSE">]">
```

**Comment by erikrose** [comment]
Thanks for the example! Would you mind if I include it in the docs when I get around to revising them?

**Comment by ibigpapa** [comment]
Feel free to include them
