### ISSUE TITLE
Is this an internal error?

### ISSUE THREAD

**Issue by ShearOfDoom** [erikrose/parsimonious#82]
I'm attempting to parse a string, `[include]x[/include]`, with this grammar:

    character = ~".*"

    any = "[any]"
    word = "[word]"
    digit = "[digit]"
    whitespace = "[whitespace]"

    not_word = "[not-word]"
    not_digit = "[not-digit]"
    not_whitespace = "[not-whitespace]"

    open_include = "[include]"
    close_include = "[/include]"
    open_exclude = "[exclude]"
    close_exclude = "[/exclude]"
    to = "[to]"

    open_start_end = "[start-end]"
    close_start_end = "[/start-end]"

    word_bound = "[word-bound]"
    open_group = "[group]"
    close_group = "[/group]"

    open_non_cap = "[non-cap]"
    close_non_cap = "[/non-cap]"

    open_pos_look = "[pos-look]"
    close_pos_look = "[/pos-look]"

    open_neg_look = "[neg-look]"
    close_neg_look = "[/neg-look]"

    zero_or_more = "[zero-or-more]"
    one_or_more = "[one-or-more]"
    zero_or_one = "[zero-or-one]"

    match_amount = ~"\\[match-amount\\s+\\d+\\]"
    match_range = ~"\\[match-range\\s+\\d+\\s+\\d+\\]"
    match_amount_more = ~"\\[match-amount-more\\s+\\d+\\]"

    or = "[or]"

And I'm getting the following error when I feed the input string through a subclass of `NodeVisitor`:

    Traceback (most recent call last):
      ...
      File "C:\Python34\lib\site-packages\parsimonious\nodes.py", line 202 in visit
        method = getattr(self, 'visit_' + node.expr_name, self.generic_visit)
    AttributeError: 'function' object has no attribute 'expr_name'  

Is this an internal error, or am I doing something wrong?

**Comment by jwhitlock** [comment]
You'll need to post your visitor too. Is this a public project?

**Comment by ShearOfDoom** [comment]
@jwhitlock Sorry about that. The visitor can be found here: https://github.com/ShearOfDoom/EasyRegex/blob/master/EasyRegex/source/visit_and_build_regex.py

**Comment by jwhitlock** [comment]
Your problem is [here](https://github.com/ShearOfDoom/EasyRegex/blob/master/EasyRegex/source/parse_easy_regex.py#L71-L72):

```python
def parse_easy_regex(easy_regex):
    """Parse an easy regex.

    This function parses an easy regex into an abstract
    syntax tree (AST). The return result from this function
    is used in the visitor.

    Keyword arguments:
    easy_regex -- The easy regex to parse.
    """
    parsed_easy_regex = create_grammar_object().parse(easy_regex)
    return parse_easy_regex
```

This code:
1. Parses the ``easy_regex`` string into a parsimonious node, then
2. Throws it away and returns the function named ``parse_easy_regex``.

Look carefully - line 71 is ``parsed`` with a ``d``, line 72 is ``parse`` without a ``d``.

I was able to diagnose this because I used an interactive debugger to see what kind of value was in ``abstract_syntax_tree``, and work backwards to the ``parse_easy_regex`` function.  You should find a way to get an interactive debugger when an exception like this is raised.  I used ipython and ipdb, but I tend to use the command line to develop.  You'll need to research how to do this in Visual Studio.  And also, assume parsimonious works, and the error is in your code.
