### ISSUE TITLE
About streaming tree processing

### ISSUE THREAD

**Issue by projetmbc** [erikrose/parsimonious#94]
Hello. Can someone clarifier the following sentences of the README by an example ?

-----------------

Some have asked why we don't process the tree as we go, SAX-style. There are two main reasons:

It wouldn't work. With a PEG parser, no parsing decision is final until the whole text is parsed. If we had to change a decision, we'd have to backtrack and redo the SAX-style interpretation as well, which would involve reconstituting part of the AST and quite possibly scuttling whatever you were doing with the streaming output.

**Comment by erikrose** [comment]
PEG parsers backtrack: we can get quite a distance into the grammar and then suddenly find that we took a wrong branch long ago. If we had been emitting tokens as we went, those tokens would have been wrong. That's why we can't do streaming processing: we'd need a way to "take back" tokens we had emitted.
